language: rust
compiler:
  - rustc
before_install:
  - wget http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
install:
  - sudo ./rust-nightly-x86_64-unknown-linux-gnu/install.sh
  - rustc -v
  - cd lib/rust-http
  - ./configure
  - make
  - cd ../..
script:
  - make build
